### ISSUE TITLE
clightning-client is not a public repo?

### ISSUE THREAD

**Issue by amunrarara** [coinos/coinos-server#60]
Hey team, 

Just curious about why the Lightning client library is not a public repo? And it is being sourced from a non-contributor to this codebase; just curious what's the reasoning there.

From package.json
`"clightning-client": "github:SimonVrouwe/lightning-client-js#2022-11-04_improve_doc"`

**Comment by amunrarara** [comment]
Bump

**Comment by asoltys** [comment]
It's published here: https://github.com/SimonVrouwe/lightning-client-js/tree/2022-11-04_improve_doc

The reason I used this fork is so I could pass objects with named parameters to CLN
