### ISSUE TITLE
Nostr zap invoice requests don't work

### ISSUE THREAD

**Issue by SamSamskies** [coinos/coinos-server#62]
Your LNURL server returns a 500 error with a message that says `Unexpected token 'm', "memo too long" is not valid JSON` when requesting invoices using [nip-57](https://github.com/nostr-protocol/nips/blob/master/57.md). Your LNURL server signals that it should work for Nostr zaps though.

```json
{
  "allowsNostr": true,
  "minSendable": 1000,
  "maxSendable": 100000000000,
  "metadata": "[[\"text/plain\",\"Paying corndalorian@coinos.io\"],[\"text/identifier\",\"corndalorian@coinos.io\"]]",
  "nostrPubkey": "b38877ef65530f09e6db43bb8ec141c38cd01f9a6436d563dddcc3b156a01365",
  "callback": "https://coinos.io/api/lnurl/4469bafa-97a1-441a-b569-4ddd9f673834",
  "tag": "payRequest"
}
```

**Comment by SamSamskies** [comment]
You are setting the memo to the nostr event which is probably most definitely more than limit of 200 characters that you have set

https://github.com/coinos/coinos-server/blob/e17a531ce983a3e2fcc233a606b9b3678e22266a/routes/lnurl.js#L103-L112

https://github.com/coinos/coinos-server/blob/e17a531ce983a3e2fcc233a606b9b3678e22266a/lib/invoices.js#L45

**Comment by asoltys** [comment]
Thanks for catching that, I increased the memo limit to 5000 for now.
