### ISSUE TITLE
bug: nwc `get_balance()` returns the balance in sats instead of msats

### ISSUE THREAD

**Issue by gzuuus** [coinos/coinos-server#65]
I have been testing your nwc implementation and notice that when I get the balance of it, it returns the balance in sats instead of msats as the nip47 spec says.: https://github.com/nostr-protocol/nips/blob/master/47.md#get_balance
I'm not familiar with your backend, but it seems that it can be solved by just converting the balance to msats in this part of the code. If its as simple as that I will be happy to open a pr to solve it.
https://github.com/coinos/coinos-server/blob/8c8c71d54d23960ffc4caa94619bae7c6a69514b/lib/nwc.ts#L112

**Comment by asoltys** [comment]
hi yeah i think it's that simple if you want to open a PR go for it

**Comment by gzuuus** [comment]
Done: https://github.com/coinos/coinos-server/pull/66
Thanks!
